version: "3.8"

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cmsdb
    depends_on:
      - mongo
    volumes:
      - ./server/uploads:/app/uploads # to persist uploads

  frontend:
    build:
      context: ./web
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
